### PR TITLE
switching to microsite from tut. #353

### PR DESCRIPTION
**Pull request by brbrown25**
@larsrh this should be all that's needed to get the site generated. I need to play around with it some more to get rid of it complaining about a non empty directory when running `makeMicrosite` as part of the `validate` command. But I figured I'd open this to make sure this is what you were looking for first.

### CODE REVIEW

**Comment by larsrh** [comment]
Build is failing; looks like there is a mismatch between Scala versions in `.travis.yml` and `build.sbt`. Could you update the version in `.travis.yml`?

**Comment by brbrown25** [comment]
> Build is failing; looks like there is a mismatch between Scala versions in `.travis.yml` and `build.sbt`. Could you update the version in `.travis.yml`?

That was my bad! I have updated the version.

**Comment by brbrown25** [comment]
hmmm looks like it's still broken after that change I'll take a look again

**Comment by brbrown25** [comment]
hmm https://github.com/scoverage/sbt-scoverage/issues/319#issuecomment-761228227 might be related

**Comment by brbrown25** [comment]
@larsrh I've downgraded the scala version as it appears there is an issue with scoverage and binary compatability. with the version bump.

**Comment by brbrown25** [comment]
Welp that broke resolve the micro site. I'll dig into this more over the weekend!

**Comment by larsrh** [comment]
Thanks a ton for your effort. If it keeps failing, just ping me again and I can try having another look.

**Comment by brbrown25** [comment]
@larsrh Thanks for the patience on this one. I forgot about some caveats of microsite when dealing with 2.12 and 2.13. I've updated the validate command to clean the docs folder so that you don't get a non empty directory error. I've also bumped the scala 2.12 and 2.13 versions as well as microsite so that this all resolves properly now. I went ahead and flattened this into a single commit so that the history can remain clean and you can accurately see what all was changed.  Let me know if you'd like any tweaks and thanks for the opportunity!

**Comment by brbrown25** [comment]
Also of note, as it stands you may need to do some additional configuration outlined [here](https://47degrees.github.io/sbt-microsites/docs/publish-with-travis/ ) to get the publish working.

**Review by larsrh — APPROVED** [review]

**Comment by larsrh** [comment]
Thanks a ton! Auto-publishing may be interesting after #346.

**Pull request merged**
