### PR TITLE
Update sbt and plugins

### PR DESCRIPTION
**Pull request by jhnsmth**

### CODE REVIEW

**Comment by larsrh** [comment]
This probably requires an update to 2.13.0-RC2, too.

**Comment by jhnsmth** [comment]
@larsrh This was my initial motivation, but I  skipped it as algebra is not published for RC2.
But the problem with the build is different, starting from v8.0 `sbt-microsites` added support for `mdoc` which is not published for scala 2.13 at all,  see 47deg/sbt-microsites#305. So the options here are  
- disable docs building for 2.13 
- downgrade the plugin back to latest release of 0.7.x which is 0.7.27
I think I'm in favor of the second one.

**Comment by larsrh** [comment]
I have no strong opinion, so feel free to follow along your preferred choice.

**Comment by jhnsmth** [comment]
@larsrh thanks, I've updated PR

**Comment by larsrh** [comment]
Thanks!

**Pull request merged**
