### PR TITLE
Deletions

### PR DESCRIPTION
**Pull request by larsrh**
This dismantles `Streaming` as far as possible, but we still have to implement some missing things here and there.

### CODE REVIEW

**Comment by adelbertc** [comment]
Oh noes we don't like `Streaming`? I've actually found myself wanting it occasionally when I want a lazy list but no `IO`.

**Comment by larsrh** [comment]
> Oh noes we don't like `Streaming`? I've actually found myself wanting it occasionally when I want a lazy list but no `IO`.

It feels like this is not the appropriate place for this type. fs2 has it, even for the pure case.

**Comment by larsrh** [comment]
@adelbertc see also #105 where @mpilquist proposed removal.

**Comment by adelbertc** [comment]
> fs2 has it, even for the pure case.

fair enough

**Comment by larsrh** [comment]
> fair enough

I'll construe that as your approval :stuck_out_tongue_winking_eye:

**Pull request merged**
