### PR TITLE
feat(migrate to gh actions): removing travis and adding configuration…

### PR DESCRIPTION
**Pull request by brbrown25**
I used https://github.com/typelevel/cats-tagless and https://github.com/typelevel/spire as inspirations and then ran `githubWorkflowGenerate` to create the workflows. I also switched around the commands a little bit.

### CODE REVIEW

**Comment by larsrh** [comment]
Coverage is failing, sadly.

**Comment by brbrown25** [comment]
> Coverage is failing, sadly.

darn I thought I had tested the coverage under 2.13, I can look at it again shortly

**Comment by larsrh** [comment]
I just pushed a change to make it use 2.12

**Review by larsrh — APPROVED** [review]
It works :shipit:

**Pull request merged**
